name: Lint Commit Messages

on:
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # 불필요한 히스토리 줄이기
      - uses: wagoid/commitlint-github-action@v5
